<?php

$labels['forgot_password']          = 'Glömt lösenord?';
$labels['recovery_password']        = 'Återställ lösenord';
$labels['phone']                    = 'Telefon';
$labels['altemail']                 = 'Alternativ e-post';
$labels['newpassword']              = 'Nytt lösenord';
$labels['newpassword_confirm']      = 'Bekräfta';
$labels['code']                     = 'Återställningskod';
$labels['question']                 = 'Hemlig fråga';
$labels['answer']                   = 'Svar till hemlig fråga';
$labels['answer_confirm']           = 'Bekräfta';
$labels['recovery']                 = 'Återställ';
$labels['save']                     = 'Spara';
$labels['cancel']                   = 'Avbryt';
$labels['email_subject']            = 'Återställ e-poståtkomst';
$labels['email_subject_admin']      = 'Återställ lösenord';
$labels['click_here']               = 'Klicka här';
$labels['no_identities']            = 'Fyll i information för återställning av lösenord.';
$labels['no_username']              = 'Ange ditt användarnamn (e-postadress)';
$labels['renew_code']               = 'Skicka ny återställningskod';
$labels['count_send_code_maximum']  = 'Maximalt antal återställningskoder har skickats!';
$labels['no_code']                  = 'Ange återställningskod';
$labels['no_answer']                = 'Ange svar på hemlig fråga';
$labels['no_password']              = 'Ange nytt lösenord';
$labels['no_password_confirm']      = 'Bekräfta nytt lösenord';
$labels['password_inconsistency']   = 'Lösenordsbekräftelse matchar inte';
$labels['password_too_short']       = 'Lösenordet måste vara minst %d tecken långt.';

$messages['disabled']               = 'Systemet är tillfälligt stängt för underhåll så återställning av lösenord är inte möjligt just nu. Vänligen försök senare. Vi ber om ursäkt för besväret.';
$messages['banned']                 = 'Tillgång är tillfälligt blockerat (för många misslyckade försök). Vänligen försök senare eller kontakta administratören.';
$messages['no_identities']          = 'Inställningarna som krävs för lösenordsåterställning har inte angetts. Vänligen %s och ange!';
$messages['user_not_found']         = 'Användare saknas';
$messages['check_account_notice']   = 'Återställningskoden har redan skickats. Vänligen kolla din e-post eller telefon.';
$messages['check_account']          = 'Återställningskod har skickats till ';
$messages['check_email']            = 'din alternativa e-postadress ';
$messages['check_sms']              = 'till din telefon';
$messages['and']                    = 'and ';
$messages['sent_to_admin']          = 'Ingen information för lösenordsåterställning hittades. Din förfrågan har skickats till administratören.';
$messages['send_failed']            = 'Kunde inte skicka koden för återställning. Försök igen senare.';
$messages['write_failed']           = 'Kunde inte spara information. Kontakta din administratör.';
$messages['code_expired']           = 'Återställningskoden har gått ut';
$messages['code_failed']            = 'Återställningskoden är ogiltig';
$messages['answer_failed']          = 'Felaktigt svar på hemlig fråga';
$messages['password_invalid']       = 'Ogiltigt lösenord';
$messages['password_check_failed']  = 'Lösenordet är för enkelt!';
$messages['password_forbidden']     = 'Lösenordet innehåller ogiltiga tecken';
$messages['password_changed']       = 'Lösenordet har uppdaterats!';
$messages['password_not_changed']   = 'Ett fel uppstod när lösenordet skulle ändras. Vänligen försök igen eller kontakta administratören.';
$messages['crypt_error']            = 'Jag kan inte spara mitt nya lösenord. Saknar kryptografisk funktion.';
$messages['connect_error']          = 'Jag kan inte spara mitt mya lösenord. Anslutningsproblem.';
$messages['password_in_history']    = 'Det här lösenordet har redan använts.';
$messages['password_const_viol']    = 'Lösenordet uppfyller inte alla krav. Det är antligen för enkelt.';
$messages['phone_invalid']          = 'Felaktigt telefonnummer! Det måsta vara %d siffror';
$messages['altemail_invalid']       = 'Den alternativa e-postadressen är felaktig!';
$messages['altemail_match_primary'] = 'Den alternativa e-postadressen kan inte vara samma som den primära e-postadressen!';

?>